const { google } = require('googleapis');
const fs = require('fs');

const auth = new google.auth.GoogleAuth({
  keyFile: 'service-account.json',
  scopes: ['https://www.googleapis.com/auth/drive']
});

const drive = google.drive({ version: 'v3', auth });

async function main() {
  try {
    const res = await drive.files.list({
      q: "name = 'Plantilla PAD CHINCHAYSULLO Julio 2026' and trashed=false",
      fields: 'files(id)'
    });
    const folderId = res.data.files[0].id;
    const files = await drive.files.list({
      q: `'${folderId}' in parents and trashed=false`,
      fields: 'files(id, name, createdTime)',
      pageSize: 1000
    });
    
    const driveFiles = files.data.files;
    const blobs = JSON.parse(fs.readFileSync('recent_blobs2.json'));
    
    const matched = {};
    driveFiles.forEach(df => {
      const match = df.name.match(/foto_(\d+)/);
      if (match) {
        const key = 'foto_' + match[1];
        
        // Let's just find the blob that has a timestamp in the pathname that is closest to createdTime?
        // No, the Vercel Blob pathname HAS THE EXACT TIMESTAMP generated by the frontend: foto_001_1784673090145.jpg
        // Does the Drive file have any relation to this timestamp?
        // Let's print out the available Vercel blob timestamps for this key, and the Drive file's createdTime
        let bTimes = [];
        blobs.forEach(b => {
          if (b.pathname.startsWith(key + '_')) {
            bTimes.push(b.uploadedAt);
          }
        });
        if(key === 'foto_145') {
          console.log(key, 'Drive:', df.createdTime, 'Blobs:', bTimes);
        }
      }
    });
  } catch(e) {
    console.error(e);
  }
}
main();
